"""
Seed Echoes with 6 hand-crafted memories so the demo has something to resonate
against on the very first submission.

Analyses are pre-written (not generated by the LLM) so seeding is fast,
deterministic, and works without an API key.

Usage:
  python seed.py            # add seed memories (idempotent — skips if already seeded)
  python seed.py --reset    # drop everything and reseed
"""
from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal, engine, init_db  # noqa: E402
from app import models  # noqa: E402


SEED = [
    {
        "author_handle": "rivka",
        "text": (
            "I was twelve when I broke my mother's favorite mug. The ceramic pieces sat on the "
            "counter for three days before I confessed. She didn't yell. She said, 'I knew the "
            "moment I saw it. I was waiting for you.' I think about that more than the breaking."
        ),
        "themes": ["honesty", "patience", "the cost of waiting"],
        "emotional_register": "tender",
        "lesson": "Some people punish you with silence; others give you room to come back.",
        "one_line_essence": "The mug, and the three days she waited",
    },
    {
        "author_handle": "isaac",
        "text": (
            "I quit my first job after eight months. It paid well, the people were fine, the work "
            "was forgettable. My friends thought I was being dramatic. I had no plan. I was twenty-three "
            "and broke and lighter. Every job since has been chosen, not accepted, and that's the "
            "only thing about that decision I'd defend."
        ),
        "themes": ["risk", "agency", "self-trust"],
        "emotional_register": "fierce",
        "lesson": "Choosing badly with intention beats choosing well by default.",
        "one_line_essence": "The job I left without a plan",
    },
    {
        "author_handle": "mira",
        "text": (
            "My grandmother taught me to play chess when I was nine. She let me win once, and I "
            "knew. I refused to play her again until I was fifteen. By then she'd had a stroke and "
            "couldn't remember the rules. I taught her, badly, and she laughed at my king moves. "
            "I miss her in moves, not in memories."
        ),
        "themes": ["pride", "regret", "love through teaching"],
        "emotional_register": "bittersweet",
        "lesson": "The years you save your dignity are the years you don't get back.",
        "one_line_essence": "Chess with my grandmother, twice",
    },
    {
        "author_handle": "dev",
        "text": (
            "I was in line at a coffee shop in Lisbon when an old man started crying quietly two "
            "people ahead of me. Nobody said anything. He paid, took his coffee, sat down, kept "
            "crying. I sat across from him without asking. We didn't speak. After about ten minutes "
            "he nodded at me and left. I think about him every time I'm sad in public."
        ),
        "themes": ["presence", "wordless kindness", "shared grief"],
        "emotional_register": "contemplative",
        "lesson": "Some forms of company don't need a reason or a sentence.",
        "one_line_essence": "The old man crying in Lisbon",
    },
    {
        "author_handle": "saoirse",
        "text": (
            "When I was nineteen I told my mother I didn't want children. She said, 'You will, you "
            "just don't know it yet.' I'm thirty-four and I still don't. We don't talk about it "
            "anymore. The not-talking is louder than the original conversation. I love her. I am "
            "tired of being told what I'll eventually want."
        ),
        "themes": ["self-knowledge", "boundaries", "being unheard"],
        "emotional_register": "raw",
        "lesson": "Love that won't believe you is its own kind of loneliness.",
        "one_line_essence": "What my mother is still waiting for",
    },
    {
        "author_handle": "tomas",
        "text": (
            "My brother and I built a treehouse in 2003 that was structurally insane. Two pallets, "
            "rope, no nails into the trunk because our father said we'd kill the tree. It collapsed "
            "the third week. We rebuilt it with nails and the tree died two summers later. He won't "
            "let me forget that we were warned. He's right. I don't remember being warned. I remember "
            "the second treehouse holding."
        ),
        "themes": ["pragmatism", "sibling memory", "the cost of solving"],
        "emotional_register": "playful",
        "lesson": "Two people can remember the same summer and learn opposite things.",
        "one_line_essence": "The tree that died for our second treehouse",
    },
]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reset", action="store_true", help="drop all tables first")
    args = parser.parse_args()

    if args.reset:
        models.Base.metadata.drop_all(bind=engine)
    init_db()

    with SessionLocal() as db:
        existing = db.query(models.Memory).count()
        if existing and not args.reset:
            print(f"Already have {existing} memories. Use --reset to wipe and reseed.")
            return

        for s in SEED:
            mem = models.Memory(
                author_handle=s["author_handle"],
                text=s["text"],
                emotional_register=s["emotional_register"],
                lesson=s["lesson"],
                one_line_essence=s["one_line_essence"],
            )
            mem.themes = s["themes"]
            db.add(mem)
        db.commit()

    print(f"Seeded {len(SEED)} memories.")
    print()
    print("Open http://localhost:5174 and write your own memory.")
    print("Claude will analyze it and pair you with the most resonant seed memory.")


if __name__ == "__main__":
    main()
